import Icon from './Icon';
export default function Dashboard({ onNavigate, stopCount, distance, routeCount }) {
  return <main className="dashboard-page">
    <div className="dash-hero"><div className="hero-copy"><span className="eyebrow"><span className="status-dot"/> YOUR CITY. BETTER CONNECTED.</span><h1>A clearer way<br/>to move through <em>Karachi.</em></h1><p>Explore your bus route, see every stop, and follow the journey in one place.</p><button className="primary-button" onClick={()=>onNavigate('tracking')}><Icon name="target"/>Open bus tracker<Icon name="arrow"/></button><span className="hero-note">{routeCount || 20} Karachi routes · Simulated fleet preview</span></div><div className="hero-route"><div className="hero-route-top"><span className="route-code">R1</span><span>THE CROSS-CITY CONNECTION</span><Icon name="bus" size={28}/></div><div className="journey-graphic"><span><i/>Khokhrapar</span><span><i/>Model Colony</span><span><i/>Shahrah-e-Faisal</span><span><i/>Saddar</span><span><i/>Dockyard</span><div className="graphic-bus"><Icon name="bus" size={24}/></div></div><div className="hero-route-bottom"><strong>{distance?.toFixed(1) || '30.4'} <small>km of connected roads</small></strong><span>{stopCount || 44} stops</span></div></div></div>
    <div className="overview-title"><div><span className="eyebrow">PLAN YOUR JOURNEY</span><h2>Everything along the way.</h2></div><span>Peoples Bus Service / Karachi</span></div>
    <div className="overview-cards"><button onClick={()=>onNavigate('tracking')}><span className="feature-icon"><Icon name="target" size={24}/></span><h3>Follow your bus</h3><p>Explore a moving fleet and estimated arrivals along R1.</p><span className="card-link">Open tracker <Icon name="arrow" size={18}/></span></button><button onClick={()=>onNavigate('route-select')}><span className="feature-icon"><Icon name="map" size={24}/></span><h3>Know your route</h3><p>Find the complete route, terminals, and stops across the city.</p><span className="card-link">Browse routes <Icon name="arrow" size={18}/></span></button><div><span className="feature-icon"><Icon name="pin" size={24}/></span><h3>Built around your city</h3><p>Detailed city streets and published stop locations across Karachi.</p><span className="quiet-pill">{routeCount || 20} routes in the directory</span></div></div>
    <footer className="dashboard-footer"><span>PBS / Karachi transit explorer</span><span>Independent prototype · Fleet data is simulated</span></footer>
  </main>;
}
